/* ReturnMessage 的返回值常量表 */

const SUCCESS = 'SUCCESS';
const ERROR = 'ERROR';
const ERROR_DATABASE = 'ERROR_DATABASE';
const INVALID_PARAM = 'INVALID_PARAM';
const NOT_FOUND = 'NOT_FOUND';
const ALREADY_CANCELED = 'ALREADY_CANCELED'; // 已经被游客取消了
const ALREADY_TIMEOUT = 'ALREADY_TIMEOUT'; // 已经过期了
const ALREADY_ACCEPTED = 'ALREADY_ACCEPTED';
const ALREADY_REJECTED = 'ALREADY_REJECTED';

export {
    SUCCESS,
    ERROR,
    ERROR_DATABASE,
    INVALID_PARAM,
    NOT_FOUND,
    ALREADY_ACCEPTED,
    ALREADY_TIMEOUT,
    ALREADY_ACCEPTED,
    ALREADY_REJECTED
}